CREATE TABLE IF NOT EXISTS Pizza
(
    pizzaId INT(4) PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(35) NOT NULL DEFAULT "Custom Pizza",
    pizzaSize INT(1) NOT NULL DEFAULT 1,
    cost DECIMAL(5, 2) NOT NULL,
    inStock BOOLEAN NOT NULL DEFAULT 1
);
